[project]
name = "d2l-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.9.23"
dependencies = [
    "d2l==0.17.6",
    "pandas>=1.2.4",
    "torch==2.8.0",
    "torchvision==0.13.0",
]
